### ISSUE TITLE
Task List #2

### ISSUE THREAD

**Issue by yooksi** [yooksi/eu4-EVE#18]
- [ ] ~~Decentralization edict should give boost to governance policy proportional to state development~~
- [x] Add more bonuses to capital state to make it on-par with reworked courthouse.
- [x] Fix a small GUI text [error ](https://github.com/yooksi/eu4-EVE/issues/17)that happens when rating is *moving to neutral*.
