### ISSUE TITLE
Task List #3

### ISSUE THREAD

**Issue by yooksi** [yooksi/eu4-EVE#23]
- [x] Write documentation for syntax highlighting.
- [x] Convert case of all scripted trigger variable arguments to _lower case_.
- [ ] <s>Redefine governance triggered modifier effects</s>.
- [x] Finish working on vassal tax rates.
- [x] Add script keywords for terrain.txt and events.
- [x] Add comments that describe customizable localisation.
- [x] Create flavor events for courthouse on_built.
- [x] Disable governance policy for low tech.
