### ISSUE TITLE
Task list #1

### ISSUE THREAD

**Issue by yooksi** [yooksi/eu4-EVE#6]
- [x] Rename monthly pulse country modifier to something else, also add a province icon to it.
- [x] ~~Add icons for country modifiers and check the error log. try maybe altering the dimensions properties of modifier window in province view if size is the problem.~~
- [x] Investigate errors mentioned in issue #4
- [x] Finish reworking the courthouse building.
- [x] Move on_is_no_longer_capital into a daily pulse check.
